# Generated by Django 5.0.6 on 2024-05-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('price', models.IntegerField()),
                ('num_bedroom', models.IntegerField()),
                ('num_bathroom', models.IntegerField()),
                ('square_meter', models.IntegerField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
